services:
    php:
        image: ${IMAGES_PREFIX:-}app-php
        restart: unless-stopped
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
            MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin}@database:5432/${POSTGRES_DB:-symfony_db}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
            MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
            MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
            MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
            # The two next lines can be removed after initial installation
            SYMFONY_VERSION: ${SYMFONY_VERSION:-}
            STABILITY: ${STABILITY:-stable}
        volumes:
            - .:/var/www/html
            - ./var/log:/var/www/html/var/log
            - caddy_data:/data
            - caddy_config:/config
        ports:
            # HTTP
            - target: 80
              published: 8080
              protocol: tcp
            # HTTPS
            - target: 443
              published: ${HTTPS_PORT:-443}
              protocol: tcp
            # HTTP/3
            - target: 443
              published: ${HTTP3_PORT:-443}
              protocol: udp
    
    # PostgreSQL Database Service
    database:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        container_name: symfony_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-symfony_db}
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-symfony_db}", "-U", "${POSTGRES_USER:-admin}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        ports:
            - "5432:5432"
        volumes:
            - database_data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw

    tailwind:
        image: node:latest
        working_dir: /app
        volumes:
            - .:/app
            - /app/node_modules
        command: ["sh", "-c", "npm install && npm run watch"]
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=1000
        stdin_open: true
        tty: true

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
volumes:
    caddy_data:
    caddy_config:
    database_data:
###< doctrine/doctrine-bundle ###
